[build]
  # Directory with the built files (relative to frontend folder)
  publish = "build/web"
  # No build command as we're using pre-built files
  command = ""

# Don't build node modules
[build.processing]
  skip_processing = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 